### ISSUE TITLE
welcomescreen.yml issue.

### ISSUE THREAD

**Issue by MaxsRepo** [TulipSMP/Tiramisu#84]
### Description

The copyright in welcomescreen.yml isn't updated to 2024, and says RoseSMP 2023 instead of Tulip SMP 2024

### Steps to reproduce

1. Check the welcomescreen.yml config file
2. Go to [this page](https://github.com/TulipSMP/Tiramisu/blob/main/config/welcomescreen.yml)
3. Look at config/welcomescreen.yml

### Platform and Version
**Operating System:** 

 GitHub on Chrome
**CPU Archetecture:** 

I use an Intel CPU. Also unrelated but I'd correct 'cpu do u have' to 'CPU do you have'
**Python Version:** 

I didn't run the script
**Tiramisu Version:**  Got no idea if it was a release, but the one on the [homepage](https://github.com/TulipSMP/Tiramisu)

Check only those that apply
- [ ] I am running straight from git 
  - Branch: 
  
- [ ] I am running a release downloaded from the releases page
  - Release number:

**Comment by TheKrafter** [comment]
fixed in [7d1eddd](https://github.com/TulipSMP/Tiramisu/commit/7d1edddaa4300eeaf128ba7f5d6debeaca34166d)
